model_config:
  class: QwenModel
  name: Qwen/Qwen3-4B
  from_pretrained_config:
    torch_dtype: auto
    device_map: auto
    quantization_config:
      load_in_8bit: false
generation_config:
  max_output_tokens: 38192
  top_p: 0.8
  min_p: 0.0
  temperature: 0.7
  top_k: 20
  enable_thinking: true
